-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- Tasks pool (pre-generated by batch process)
create table tasks (
  id uuid primary key default uuid_generate_v4(),
  type text not null check (type in (
    'rapid_fire_qa',
    'taboo_paraphrase',
    'ted_listening',
    'news_headline',
    'visual_impression',
    'situation_survival',
    'emotion_sharing',
    'pattern_practice'
  )),
  category text not null check (category in ('warmup', 'input', 'output')),
  content jsonb not null,
  difficulty int default 1 check (difficulty between 1 and 3),
  created_at timestamptz default now(),
  active boolean default true
);

-- Task completions log
create table task_completions (
  id uuid primary key default uuid_generate_v4(),
  user_id uuid references auth.users(id) on delete cascade not null,
  task_id uuid references tasks(id) on delete set null,
  task_type text not null,
  transcript text,
  feedback jsonb,
  completed_at timestamptz default now()
);

-- Learned expressions stock
create table learned_expressions (
  id uuid primary key default uuid_generate_v4(),
  user_id uuid references auth.users(id) on delete cascade not null,
  original_input text not null,
  corrected_text text,
  inline_correction jsonb,
  native_expressions text[],
  error_explanation text,
  task_type text,
  created_at timestamptz default now()
);

-- Activity logs for heatmap
create table activity_logs (
  id uuid primary key default uuid_generate_v4(),
  user_id uuid references auth.users(id) on delete cascade not null,
  date date not null,
  task_count int default 0,
  created_at timestamptz default now(),
  unique(user_id, date)
);

-- RLS policies
alter table task_completions enable row level security;
alter table learned_expressions enable row level security;
alter table activity_logs enable row level security;

create policy "Users can only access their own completions"
  on task_completions for all using (auth.uid() = user_id);

create policy "Users can only access their own expressions"
  on learned_expressions for all using (auth.uid() = user_id);

create policy "Users can only access their own activity"
  on activity_logs for all using (auth.uid() = user_id);

create policy "Tasks are readable by authenticated users"
  on tasks for select using (auth.role() = 'authenticated');

-- Seed data: Master tasks (static tasks that don't expire)
insert into tasks (type, category, content, difficulty) values

-- Rapid Fire Q&A (warmup)
('rapid_fire_qa', 'warmup', '{
  "questions": [
    "What did you have for breakfast today?",
    "Do you prefer summer or winter?",
    "What''s your favorite way to spend a Sunday?",
    "Would you rather work from home or in an office?",
    "What''s one thing you''re looking forward to this week?"
  ]
}', 1),

('rapid_fire_qa', 'warmup', '{
  "questions": [
    "What''s the last movie or show you watched?",
    "Mountains or beach — which would you choose?",
    "What''s your go-to comfort food?",
    "Do you consider yourself a morning person or a night owl?",
    "What''s one skill you''d love to master?"
  ]
}', 1),

('rapid_fire_qa', 'warmup', '{
  "questions": [
    "What''s your favorite season and why?",
    "If you could travel anywhere tomorrow, where would you go?",
    "Coffee or tea?",
    "What was the last thing that made you laugh?",
    "What hobby have you always wanted to try?"
  ]
}', 1),

-- Taboo Paraphrase (warmup)
('taboo_paraphrase', 'warmup', '{
  "word": "Smartphone",
  "forbidden": ["phone", "screen", "app", "call", "mobile"],
  "hint": "A device almost everyone carries today"
}', 2),

('taboo_paraphrase', 'warmup', '{
  "word": "Restaurant",
  "forbidden": ["food", "eat", "menu", "cook", "meal"],
  "hint": "A place you go with friends or family"
}', 1),

('taboo_paraphrase', 'warmup', '{
  "word": "Library",
  "forbidden": ["book", "read", "borrow", "study", "quiet"],
  "hint": "A public place you can visit for free"
}', 1),

('taboo_paraphrase', 'warmup', '{
  "word": "Commute",
  "forbidden": ["train", "bus", "work", "travel", "transport"],
  "hint": "Something many people do every morning and evening"
}', 2),

('taboo_paraphrase', 'warmup', '{
  "word": "Password",
  "forbidden": ["secret", "login", "code", "security", "account"],
  "hint": "Something you create when you sign up for a new service"
}', 2),

-- TED Listening (input)
('ted_listening', 'input', '{
  "youtube_id": "iG9CE55wbtY",
  "title": "Do schools kill creativity? — Sir Ken Robinson",
  "question": "What is the speaker''s main argument, and do you agree with it? Share your thoughts in 3 sentences."
}', 2),

('ted_listening', 'input', '{
  "youtube_id": "arj7oStGLkU",
  "title": "Inside the mind of a master procrastinator — Tim Urban",
  "question": "Describe the concept of the ''Instant Gratification Monkey'' in your own words. Can you relate to it?"
}', 2),

('ted_listening', 'input', '{
  "youtube_id": "H14bBuluwB8",
  "title": "How to speak so that people want to listen — Julian Treasure",
  "question": "What is one tip from this talk that you want to apply in your own life? Explain why."
}', 2),

-- News Headlines (input)
('news_headline', 'input', '{
  "headlines": [
    "Tech Giants Race to Deploy AI Agents That Can Browse the Web Autonomously",
    "Scientists Discover New Method to Store Solar Energy for Weeks",
    "Remote Work Trend Reverses as Major Corporations Mandate Office Returns"
  ]
}', 1),

('news_headline', 'input', '{
  "headlines": [
    "Electric Vehicle Sales Surge in Asia While Europe Faces Slowdown",
    "Startup Raises $500M to Build Next-Generation Nuclear Fusion Reactor",
    "Social Media Platforms Introduce AI Content Labeling for All Posts"
  ]
}', 1),

('news_headline', 'input', '{
  "headlines": [
    "Japan Introduces Four-Day Workweek Pilot for Government Employees",
    "Global Coffee Prices Hit Record High Due to Climate-Related Crop Failures",
    "New Study Links Excessive Screen Time to Declining Attention Spans in Adults"
  ]
}', 1),

-- Visual Impression (output)
('visual_impression', 'output', '{
  "image_url": "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800",
  "prompt": "Look at this image. What do you feel? What does it remind you of? Speak freely for 30-60 seconds."
}', 1),

('visual_impression', 'output', '{
  "image_url": "https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=800",
  "prompt": "Describe what you see in this image and what emotions it evokes. Would you want to visit this place? Why or why not?"
}', 1),

('visual_impression', 'output', '{
  "image_url": "https://images.unsplash.com/photo-1454496522488-7a8e488e8606?w=800",
  "prompt": "What story does this image tell you? Who do you imagine lives or works here?"
}', 1),

-- Situation Survival (output)
('situation_survival', 'output', '{
  "situation": "レストランで注文した料理と全く違うものが運ばれてきました。どう対応しますか？",
  "scenario_en": "The wrong dish was served at a restaurant"
}', 1),

('situation_survival', 'output', '{
  "situation": "友人が待ち合わせに1時間も遅刻してきました。どう声をかけますか？",
  "scenario_en": "Your friend is 1 hour late to your meetup"
}', 1),

('situation_survival', 'output', '{
  "situation": "英語で道を聞かれましたが、知らない場所でした。どう答えますか？",
  "scenario_en": "Someone asks you for directions in English but you don''t know the place"
}', 1),

('situation_survival', 'output', '{
  "situation": "外国人の同僚があなたの仕事ぶりを褒めてくれました。謙虚に、でも素直に返答してください。",
  "scenario_en": "A foreign colleague compliments your work"
}', 1),

('situation_survival', 'output', '{
  "situation": "オンライン会議中に相手の声が聞こえなくなってしまいました。確認してください。",
  "scenario_en": "Someone''s audio cuts out during an online meeting"
}', 1),

-- Emotion & Idea Sharing (output)
('emotion_sharing', 'output', '{
  "prompt": "最近買ってよかったものについて話してください。なぜ気に入っているのか、英語で説明してみましょう。",
  "prompt_en": "Talk about something you recently bought and are happy with."
}', 1),

('emotion_sharing', 'output', '{
  "prompt": "究極の選択：山と海、どちらが好きですか？理由も含めて英語で話してください。",
  "prompt_en": "Mountains or ocean — which do you prefer and why?"
}', 1),

('emotion_sharing', 'output', '{
  "prompt": "もし明日から1ヶ月休みが取れるとしたら、何をしますか？英語で夢を語ってください。",
  "prompt_en": "If you had a month off starting tomorrow, what would you do?"
}', 1),

('emotion_sharing', 'output', '{
  "prompt": "くだらないけど面白いビジネスアイデアを英語でプレゼンしてください。（例：猫カフェの逆、人間カフェ）",
  "prompt_en": "Pitch a silly but creative business idea in English."
}', 2),

('emotion_sharing', 'output', '{
  "prompt": "あなたが子供の頃に夢中だったものは何ですか？今も好きですか？英語で話してください。",
  "prompt_en": "What were you obsessed with as a child? Are you still into it?"
}', 1),

-- Pattern Practice (output)
('pattern_practice', 'output', '{
  "japanese": "しょうがない",
  "explanation": "It can''t be helped / There''s nothing we can do about it",
  "hint": "Use it when accepting an unfortunate situation beyond your control"
}', 2),

('pattern_practice', 'output', '{
  "japanese": "空気を読む",
  "explanation": "Reading the room / Sensing the atmosphere",
  "hint": "The ability to understand unspoken social expectations"
}', 3),

('pattern_practice', 'output', '{
  "japanese": "お疲れ様でした",
  "explanation": "Good work today / Thanks for your hard work",
  "hint": "Said at the end of the workday to acknowledge someone''s efforts"
}', 2),

('pattern_practice', 'output', '{
  "japanese": "よろしくお願いします",
  "explanation": "Nice to meet you / I look forward to working with you / Please take care of this",
  "hint": "Context-dependent phrase used when making a request or building a relationship"
}', 2),

('pattern_practice', 'output', '{
  "japanese": "なんとかなる",
  "explanation": "It''ll work out somehow / Things will be fine",
  "hint": "An optimistic expression used when facing uncertainty"
}', 2);
